name: Deploy book to Github Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    env:
      MDBOOK_VERSION: 0.5.2

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install mdbook
        run: cargo install --version ${MDBOOK_VERSION} mdbook

      - name: Build book
        run: mdbook build book

      - name: Setup Github Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Upload artifact to Github Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book/book

  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
