name: Pull requests workflow

on:
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev pkg-config

      - name: Run tests
        run: cargo test